export const LOAD_USER_PAGE = 'USER_PAGE/LOAD_USER_PAGE';
export const LOAD_USER_PAGE_SUCCESS = 'USER_PAGE/LOAD_USER_PAGE_SUCCESS';
export const LOAD_USER_PAGE_ERROR = 'USER_PAGE/LOAD_USER_PAGE_ERROR';